name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.27.0

      - name: Install dependencies
        run: pnpm install

      - name: Build kernel-shared
        run: pnpm run build:packages

      - name: Build app
        run: pnpm run build

      - name: Auto generate cname file
        run: |
          echo "imtaotao.me" > ./app/dist/CNAME
          echo "CNAME file created with content: www.imtaotao.me"

      - name: Auto generate wx file
        run: |
          echo "637c3f02747e5902d8af99968a7dc43296630950" > ./app/dist/467aa3479feeea161c90dcc396ea3ee4.txt
          echo "wx file created with content: 637c3f02747e5902d8af99968a7dc43296630950"

      - name: Deploy app to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
